<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>apex</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>name</key>
	<string>Apex</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(?i:package|trigger|class|interface)\b</string>
			<key>name</key>
			<string>storage.type.apex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:webservice|testmethod)\b</string>
			<key>name</key>
			<string>keyword.control.annotation.apex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:commit|rollback)\b</string>
			<key>name</key>
			<string>keyword.control.transaction.apex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:insert|update|delete)\b</string>
			<key>name</key>
			<string>keyword.control.dml.apex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:webservice|testmethod)\b</string>
			<key>name</key>
			<string>keyword.control.annotation.apex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:try|catch|finally|throw)\b</string>
			<key>name</key>
			<string>keyword.control.catch-exception.apex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:return|break|case|continue|default|do|while|for|switch|if|else)\b</string>
			<key>name</key>
			<string>keyword.control.apex</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</key>
		</dict>
		<dict>
			<key>include</key>
			<string>#support-type-built-ins-apex</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.soql.begin.apex</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.soql.end.apex</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.brackets.soql.apex</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.block.empty.apex</string>
					<key>match</key>
					<string>/\*\*/</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.apex</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments-inline</string>
				</dict>
			</array>
		</dict>
		<key>comments-inline</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.block.apex</string>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.apex</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\s*((//).*$\n?)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment.line.double-slash.apex</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.apex</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.apex</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.apex</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.apex</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.apex</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>support-type-built-ins-apex</key>
		<dict>
			<key>match</key>
			<string>\b(?i:integer|string|void|double|boolean|date|datetime|id)\b</string>
			<key>name</key>
			<string>support.type.built-ins.apex</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.apex</string>
	<key>uuid</key>
	<string>C4D3A5F4-B1DE-48C5-84CE-AC99DDA78292</string>
</dict>
</plist>
